Final task
xbulat/simpler pull request #1
Opened 2019-01-07 21:43 UTC by xbulat

Support  HTML & Plain render
Support custom response code
Support custom header
Support routes with params
Add middleware logger

2019-01-08 10:01 UTC, iBublik requested changes

2019-01-08 10:01 UTC, iBublik commented on lib/simpler/controller.rb
> +    def set_headers(type = nil)
`type = :plain` и не придется в `fetch` дефолтное значение указывать

2019-01-08 10:01 UTC, iBublik commented on lib/simpler/controller.rb
> +    def header
Лучше назвать `headers`, ведь там не один заголовок

2019-01-08 10:01 UTC, iBublik commented on lib/simpler/controller.rb
> +      @response['Content-Type'] = HEADERS.fetch(type, 'text/html')
У метода общее название, хотя он устанавливает только 1 заголовок - это сбивает с толку. Я бы оставил метод `set_default_headers`,  он скорее всего будет расширяться. Можно устанавливать дефолтные хедеры только если они еще не заданы (`headers[...] ||= ...`)

2019-01-08 10:01 UTC, iBublik commented on lib/simpler/router/route.rb
> +        @request_path = env['PATH_INFO']
Можно было использовать `Rack::Request`, чтоб не возиться с env

2019-01-08 10:01 UTC, iBublik commented on lib/simpler/router/route.rb
> +        env['simpler.params'] = params(@request_path) if path_with_params?
Тут должны быть все параметры - не только из строки запроса, но и из форм

2019-01-08 10:01 UTC, iBublik commented on lib/simpler/router/route.rb
> +        Regexp.new(path.gsub(/\:\w+/, '\d+') + '$')
Параметры не обязаны быть числами, например это может быть слаг (`/posts/learning-ruby` => `/posts/:slug`)

2019-01-08 10:01 UTC, iBublik commented on lib/simpler/router/route.rb
> +        @path.match(/\:(\w+)/)[1]
В маршруте может быть указано произвольное число параметров (`/categories/:category_id/tests/:id`)

2019-01-09 06:12 UTC, iBublik requested changes

2019-01-09 06:12 UTC, iBublik commented on app/controllers/tests_controller.rb
> +    header['Content-Type'] = 'text/plain'
У тебя уже нет метод `header`
К тому же, вручную указывать Content-Type как-то муторно. Он должен автоматически устанавливаться в зависимости от типа рендеринга

2019-01-09 06:12 UTC, iBublik commented on lib/simpler/controller.rb
> +    def set_headers(type = :html)
Название все так же слишком общее. Раз тут установка только Content-Type, то и назови `set_content_type` или как-то так

2019-01-09 06:12 UTC, iBublik commented on lib/simpler/controller.rb
> +      @response['Content-Type'] = HEADERS.fetch(type)
Лучше работай со своим методом `header`, так понятнее

2019-01-09 06:12 UTC, iBublik commented on lib/simpler/controller.rb
>        @response['Content-Type'] = 'text/html'
У тебя сейчас работа кода неявно зависит от порядка вызова методов. Если ты вызовешь set_default_headers после вызова рендеринга, то всегда будет дефолтный Content-Type. Дефолтные хедеры нужно устанавливать _только если они еще не указаны_

2019-01-09 06:12 UTC, iBublik commented on lib/simpler/router/route.rb
> +        @path_regexp = path_regexp(path)
Зачем ты передаешь параметром то, что всегда доступно через инстанс-переменную?

2019-01-09 06:12 UTC, iBublik commented on lib/simpler/router/route.rb
> +        @request = Rack::Request.new(env)
Уже писал, что менять состояния после инициализации объекта - скользкая дорожка, можно очень больно себе в ногу выстрелить. Зачем это делать инстанс-переменной? Можно ведь просто параметры пробрасывать в методы

2019-01-09 06:12 UTC, iBublik commented on lib/simpler/router/route.rb
> +        params(@request_path) if path_with_params? || {}
Этот метод полагается, что где-то ранее будет создана инстасн-переменная `@request_path`. Публичный интерфейс не должен быть таким хрупким - не тот порядок вызова методов просто сломает класс. Здесь опять же лучше все явно в метод передавать параметрами

2019-01-09 06:12 UTC, iBublik commented on lib/simpler/router/route.rb
> +        Regexp.new(@path.gsub(/\:\w+/) {|e| "(?<#{e.delete(':')}>\\w+)"})
Раздели лучше на несколько строк, сейчас все в кашу и плохо читается

2019-01-09 06:12 UTC, iBublik commented on lib/simpler/view.rb
> +      template = env.keys.select { |type| type.match(/simpler.template./) }
Попробуй тут `grep` использовать вместо `select` + `match`

2019-01-09 06:12 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['simpler.params'] = params.merge(@request.params.transform_keys(&:to_sym))
Ок, ты записал параметры в env, а где метод для получения этих параметров?

2019-01-09 11:20 UTC, xbulat commented on lib/simpler/controller.rb
> +      @request.env['simpler.params'] = params.merge(@request.params.transform_keys(&:to_sym))
```
    def params
      @request.env['simpler.params']
end
```

2019-01-11 07:46 UTC, iBublik approved these changes

2019-01-11 07:46 UTC, iBublik commented on lib/simpler/application.rb
> +      controller.set_params(route.route_params(controller.request.path_info))
Очень громоздкая запись получилась. Можно было в роутере устанавливать параметры роутинга, а в контроллере просто добавлять туда параметры запроса

2019-01-11 07:46 UTC, iBublik commented on lib/simpler/controller.rb
> +      headers['Content-Type'] = 'text/html' if headers['Content-Type'].nil?
`headers[...] ||= ...`

2019-01-11 07:46 UTC, iBublik commented on lib/simpler/view.rb
> +      template = env.keys.grep(/simpler\.template\.(\w+)/){$1}
Использование `$1` довольно неявная штука, избегай таких "перлизмов"
А почему просто не хранить в отдельном ключе тип рендеринга, чтоб так не извращаться?

2020-10-04 19:22 UTC, closed without merging